const COLOR_PRIMARY = "#007bff";
const COLOR_SECONDARY = "#6c757d";
const COLOR_SUCCESS = "#28a745";
const COLOR_MUTED = "#6c757d";
const COLOR_LIGHT = "#f8f9fa";

export {
    COLOR_PRIMARY,
    COLOR_SECONDARY,
    COLOR_SUCCESS,
    COLOR_LIGHT,
    COLOR_MUTED
}